import type { Cliente, SupervisorResumo } from "./types"

// Estrutura comercial (supervisores -> vendedores) conforme documentação
export const MOCK_SUPERVISORES: SupervisorResumo[] = [
  {
    codigo: 100,
    nome: "Supervisor 100",
    tipo: "supervisor",
    total_clientes: 42,
    vendedores: [
      { codigo: 101, nome: "Vendedor 101", tipo: "vendedor", total_clientes: 12 },
      { codigo: 102, nome: "Vendedor 102", tipo: "vendedor", total_clientes: 10 },
      { codigo: 103, nome: "Vendedor 103", tipo: "vendedor", total_clientes: 11 },
      { codigo: 104, nome: "Vendedor 104", tipo: "vendedor", total_clientes: 9 },
    ],
  },
  {
    codigo: 200,
    nome: "Supervisor 200",
    tipo: "supervisor",
    total_clientes: 64,
    vendedores: [
      { codigo: 201, nome: "Vendedor 201", tipo: "vendedor", total_clientes: 14 },
      { codigo: 202, nome: "Vendedor 202", tipo: "vendedor", total_clientes: 9 },
      { codigo: 203, nome: "Vendedor 203", tipo: "vendedor", total_clientes: 11 },
      { codigo: 204, nome: "Vendedor 204", tipo: "vendedor", total_clientes: 8 },
      { codigo: 205, nome: "Vendedor 205", tipo: "vendedor", total_clientes: 12 },
      { codigo: 206, nome: "Vendedor 206", tipo: "vendedor", total_clientes: 10 },
    ],
  },
  {
    codigo: 400,
    nome: "Supervisor 400",
    tipo: "supervisor",
    total_clientes: 51,
    vendedores: [
      { codigo: 401, nome: "Vendedor 401", tipo: "vendedor", total_clientes: 9 },
      { codigo: 402, nome: "Vendedor 402", tipo: "vendedor", total_clientes: 11 },
      { codigo: 403, nome: "Vendedor 403", tipo: "vendedor", total_clientes: 8 },
      { codigo: 404, nome: "Vendedor 404", tipo: "vendedor", total_clientes: 7 },
      { codigo: 405, nome: "Vendedor 405", tipo: "vendedor", total_clientes: 8 },
      { codigo: 406, nome: "Vendedor 406", tipo: "vendedor", total_clientes: 8 },
    ],
  },
  {
    codigo: 800,
    nome: "BALCÃO",
    tipo: "balcao",
    total_clientes: 23,
    vendedores: [
      { codigo: 301, nome: "Balcão 301", tipo: "balcao", total_clientes: 13 },
      { codigo: 501, nome: "Vendedor 501", tipo: "vendedor", total_clientes: 10 },
    ],
  },
]

function contratosFake(seed: number) {
  return [
    {
      numero_contrato: `04${8670 + seed}`,
      emissao: "2026-06-23",
      vencimento: "2026-06-30",
      tipo: "Provisório" as const,
      status: "vencido" as const,
      produtos: [
        { codigo_produto: "49721", descricao: "REFR VT VN PC DEV", quantidade: 10 },
        { codigo_produto: "49721", descricao: "REFR VT VN PC DEV", quantidade: 5 },
        { codigo_produto: "49721", descricao: "REFR VT VN PC DEV", quantidade: 100 },
      ],
    },
    {
      numero_contrato: `05${4770 + seed}`,
      emissao: "2026-06-23",
      vencimento: "2026-10-30",
      tipo: "Fixo" as const,
      status: "ativo" as const,
      produtos: [
        { codigo_produto: "50112", descricao: "CHOPP PILSEN BARRIL", quantidade: 4 },
        { codigo_produto: "50118", descricao: "CO2 CILINDRO 6KG", quantidade: 2 },
      ],
    },
  ]
}

export const MOCK_CLIENTES: Cliente[] = [
  {
    codigo_cliente: "0001-7871",
    nome_fantasia: "BAR DO EDESIO",
    razao_social: "Alisson Rodrigues",
    cidade: "IRECÊ",
    rota: "1",
    vendedor: { codigo: 201, nome: "Vendedor 201", tipo: "vendedor" },
    supervisor: { codigo: 200, nome: "Supervisor 200", tipo: "supervisor" },
    total_contratos: 2,
    contratos_ativos: 1,
    contratos_vencidos: 1,
    contratos_a_vencer: 0,
    contratos: contratosFake(9),
  },
  {
    codigo_cliente: "0001-7872",
    nome_fantasia: "BAR DO FABIO",
    razao_social: "Fabio Souza",
    cidade: "SEABRA",
    rota: "1",
    vendedor: { codigo: 201, nome: "Vendedor 201", tipo: "vendedor" },
    supervisor: { codigo: 200, nome: "Supervisor 200", tipo: "supervisor" },
    total_contratos: 1,
    contratos_ativos: 0,
    contratos_vencidos: 1,
    contratos_a_vencer: 0,
    contratos: contratosFake(3),
  },
  {
    codigo_cliente: "0024-0315",
    nome_fantasia: "BEBIDAS CHAGAS",
    razao_social: "Laura Chagas da Silva",
    cidade: "XIQUE-XIQUE",
    rota: "1",
    vendedor: { codigo: 201, nome: "Vendedor 201", tipo: "vendedor" },
    supervisor: { codigo: 200, nome: "Supervisor 200", tipo: "supervisor" },
    total_contratos: 1,
    contratos_ativos: 0,
    contratos_vencidos: 1,
    contratos_a_vencer: 0,
    contratos: contratosFake(1),
  },
  {
    codigo_cliente: "0024-0317",
    nome_fantasia: "MERCADINHO POPULAR",
    razao_social: "Comercial Popular LTDA",
    cidade: "XIQUE-XIQUE",
    rota: "2",
    vendedor: { codigo: 201, nome: "Vendedor 201", tipo: "vendedor" },
    supervisor: { codigo: 200, nome: "Supervisor 200", tipo: "supervisor" },
    total_contratos: 2,
    contratos_ativos: 1,
    contratos_vencidos: 1,
    contratos_a_vencer: 0,
    contratos: contratosFake(5),
  },
  {
    codigo_cliente: "0010-1102",
    nome_fantasia: "RESTAURANTE DA PRACA",
    razao_social: "Maria Restaurante ME",
    cidade: "IRECÊ",
    rota: "1",
    vendedor: { codigo: 101, nome: "Vendedor 101", tipo: "vendedor" },
    supervisor: { codigo: 100, nome: "Supervisor 100", tipo: "supervisor" },
    total_contratos: 1,
    contratos_ativos: 1,
    contratos_vencidos: 0,
    contratos_a_vencer: 0,
    contratos: contratosFake(7),
  },
  {
    codigo_cliente: "0040-2200",
    nome_fantasia: "DEPOSITO CENTRAL",
    razao_social: "Distribuidora Central SA",
    cidade: "BARRA",
    rota: "3",
    vendedor: { codigo: 402, nome: "Vendedor 402", tipo: "vendedor" },
    supervisor: { codigo: 400, nome: "Supervisor 400", tipo: "supervisor" },
    total_contratos: 1,
    contratos_ativos: 0,
    contratos_vencidos: 1,
    contratos_a_vencer: 0,
    contratos: contratosFake(2),
  },
]
